- hosts: "{{ server_ip }}"
  remote_user: root
  tasks:
    - name: Test python version.
      test_python_version:
      delegate_to: python3
      register: version_output

    - debug:
       msg: "{{version_output}}"

    - name: Test domain name.
      test_domain_name:
       domain_name: "{{ domain_name }}"
      delegate_to: python3
      register: domain_output


    - debug:
       msg: "{{domain_output}}"
